Backported changes from upstream + modified our changes to be more compatible with upstream

diff --git a/lib/svc/method/fs-joyent b/lib/svc/method/fs-joyent
--- a/lib/svc/method/fs-joyent
+++ b/lib/svc/method/fs-joyent
@@ -20,14 +20,14 @@
 # CDDL HEADER END
 #
 # Copyright 2014, Joyent, Inc. All rights reserved.
-# Copyright 2016, Erigones, Ltd.
+# Copyright 2017, Erigones, s. r. o.
 
 set -o xtrace
 
 fatal()
 {
     echo "Error: $1"
-        exit $SMF_EXIT_ERR_FATAL
+    exit $SMF_EXIT_ERR_FATAL
 }
 
 . /lib/svc/share/smf_include.sh
@@ -89,7 +89,7 @@ function make_usb_copy
     if [[ -d ${USBMOUNTPOINT}/os ]]; then
         (cd ${USBMOUNTPOINT}/os ; \
             for dir in $(ls -d *); do
-                # source comes from pcfs which we have got lowering the case
+                # source comes from pcfs which we've got lowering the case
                 # of everything, but we normally use capital T and Z for
                 # buildstamp, so fix it here.
                 source_dir=${dir}
@@ -138,8 +138,9 @@ if [ ${BOOTED_FROM_HDD} -ne 0 ]; then
 fi
 
 /bin/bootparams | grep "^noimport=true" >/dev/null
-# rc = 1 when noimport != true, so import the pools!
 if [ $? -ne 0 ]; then
+    # If the zpool doesn't exist, then there's nothing to mount.
+
     # Import specified zpools, or all zpools available
     pools=$(/bin/bootparams | egrep "^zpools?=" | cut -d= -f2 | tr , ' ')
     if [ -z ${pools} ]; then
@@ -156,7 +157,7 @@ if [ $? -ne 0 ]; then
         # Determine the system pool (only ONE can be system pool) when
         # we run from live image
         if [[ ${BOOTED_FROM_HDD} -ne 1 && -f /${pool}/.system_pool ]]; then
-            SYS_ZPOOL=${pool}
+            SYS_ZPOOL=$pool
         fi
     done
 
@@ -168,8 +169,9 @@ if [ $? -ne 0 ]; then
         config/zpool=${SYS_ZPOOL}
     svccfg -s svc:/system/smartdc/init:default refresh
 
-    # Can destry pools only when running from USB
+    # Can destroy pools only when running from USB
     if [ ${BOOTED_FROM_HDD} -eq 0 ]; then
+
         # If the destroy_zpools boot parameter is set, destroy all zpools
         /bin/bootparams | grep "^destroy_zpools=true" >/dev/null
         if [ $? -eq 0 ]; then
@@ -179,7 +181,7 @@ if [ $? -ne 0 ]; then
         # A machine is reset to its original unsetup state (i.e. a 'factory reset')
         # when the smartdc:factoryreset ZFS user property is set on the var dataset.
         reset=$(zfs get -H -o value smartdc:factoryreset ${SYS_ZPOOL}/var)
-        if [ "${reset}" == "yes" ]; then
+        if [ ${reset} == "yes" ]; then
             destroy_zpools
         fi
     fi
@@ -187,6 +189,10 @@ if [ $? -ne 0 ]; then
     # For the system zpool, mount and configure all system datasets
     zpool status -v ${SYS_ZPOOL}
     if [ $? -eq 0 ]; then
+        # Stash the SUNWdefault.xml file so we can update the
+        # persistent version after mounting zones/config.
+        cp /etc/zones/SUNWdefault.xml /tmp/
+
         if [[ -n $(/bin/bootparams | grep '^headnode=true') || \
             -n $(/bin/bootparams | grep '^computenode=true') ]]; then
             mkdir /usbkey
@@ -208,16 +214,19 @@ if [ $? -ne 0 ]; then
         mount_zfs ${SYS_ZPOOL}/config /etc/zones
         mount_zfs ${SYS_ZPOOL}/opt /opt
 
+        # Update the the persistent SUNWdefault.xml file to match the
+        # contents on ramdisk now that zones/config is mounted.
+        cp /tmp/SUNWdefault.xml /etc/zones/
+        rm -f /tmp/SUNWdefault.xml
+
         if [[ -z $(/bin/bootparams | grep '^computenode=true') ]]; then
             mkdir -p /opt/smartdc/agents/smf
             mount -O -F lofs /var/svc/manifest/site /opt/smartdc/agents/smf
         fi
 
         _swapdev=/dev/zvol/dsk/${SYS_ZPOOL}/swap
-        (swap -l | grep -q ^${_swapdev})
-        if [ $? -ne 0 ]; then
-            swap -a ${_swapdev} || \
-                fatal "failed to configure swap device"
+        if ! swap -l | grep -q ^${_swapdev}; then
+            swap -a ${_swapdev} || fatal "failed to configure swap device"
         fi
 
         #
@@ -234,130 +243,135 @@ if [ $? -ne 0 ]; then
             fatal "failed to set checksum=noparity on dump zvol"
         zpool set feature@multi_vdev_crash_dump=enabled ${SYS_ZPOOL} || \
             fatal "failed to enable multi_vdev_crash_dump ZFS feature"
-        _dumpdev=/dev/zvol/dsk/${SYS_ZPOOL}/dump
+        _dumpdev=/dev/zvol/dsk/${SYS_ZPOOL}/dum
         dumpadm -y -d ${_dumpdev} || \
-                fatal "failed to configure dump device"
+            fatal "failed to configure dump device"
 
-        zfs list -H -o name ${SYS_ZPOOL}/cores/global >/dev/null 2>&1
-        if [ $? -ne 0 ]; then
-            # Booting for the first time on a CN whose cores dataset is setup
-            # in the 6.x style.  Convert to the new style.
-            zfs destroy -r ${SYS_ZPOOL}/cores
-            zfs create -o compression=gzip -o mountpoint=none ${SYS_ZPOOL}/cores
-            zfs create -o quota=10g -o mountpoint=/${SYS_ZPOOL}/global/cores \
-                ${SYS_ZPOOL}/cores/global
-            ln -s /${SYS_ZPOOL}/global/cores /cores
-        fi
+	zfs list -H -o name ${SYS_ZPOOL}/cores/global >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+	    # Booting for the first time on a CN whose cores dataset is setup
+	    # in the 6.x style.  Convert to the new style.
+	    zfs destroy -r ${SYS_ZPOOL}/cores
+	    zfs create -o compression=gzip -o mountpoint=none ${SYS_ZPOOL}/cores
+	    zfs create -o quota=10g -o mountpoint=/${SYS_ZPOOL}/global/cores \
+	        ${SYS_ZPOOL}/cores/global
+	fi
+
+	ln -s /${SYS_ZPOOL}/global/cores /cores
+
+	[[ -f /${SYS_ZPOOL}/currbooted ]] && \
+            mv /${SYS_ZPOOL}/currbooted /${SYS_ZPOOL}/lastbooted
+	uname -v >/${SYS_ZPOOL}/currbooted
     fi
 fi
 
-if [ ${BOOTED_FROM_HDD} -eq 0 ]
-then
-    # The rest only applies to the headnode and computenode, not standalone system
-    /bin/bootparams | egrep "^(headnode=true|computenode=true)" >/dev/null || exit $SMF_EXIT_OK
-
-    # If we rebooted during an upgrade, we're in deep trouble.
-    if [ -d /var/upgrade_in_progress ]; then
-        echo "ERROR: An upgrade was in progress when the system rebooted." \
-            >/dev/console
-        echo "       The system is in an indeterminate state, unable to continue." \
-            >/dev/console
-        exit $SMF_EXIT_ERR_FATAL
-    fi
-
-    mount_usb_msg=""
-
-    if [[ -d /mnt ]]; then
-        chown root:root /mnt
-        chmod 700 /mnt
-    else
-        mkdir -m 700 /mnt
-    fi
-
-    mkdir -p ${USBMOUNTPOINT}
-
-    if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-        mount_usb_msg="already mounted"
-
-        zpool list | grep ${SYS_ZPOOL}
-        if [[ $? == 0 ]]; then
-            make_usb_copy
-            exit $?
-        fi
-        echo "Running from USB..." > /dev/console
-        exit 0;
-    fi
-
-    # First thing to do is to mount the USB key / VMWare disk
-    USBKEYS=`/usr/bin/disklist -a`
-    for key in ${USBKEYS}; do
-        if [[ `/usr/sbin/fstyp /dev/dsk/${key}p0:1` == 'pcfs' ]]; then
-            /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${key}p0:1 \
-                ${USBMOUNTPOINT};
-            if [[ $? == "0" ]]; then
-                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                    fi
-                    /usr/sbin/umount ${USBMOUNTPOINT};
-                else
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                    fi
-                    break;
-                fi
-            elif [[ ${DEBUG} == "true" ]]; then
-                mount_usb_msg="${mount_usb_msg}\n[debug] mount failed for pcfs /dev/dsk/${key}p0:1"
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${key}p0:1 is not pcfs"
-        fi
-    done
-
-    if [[ ! -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-        # we're probably VMWare, so we're looking at a non-USB disk.
-        for disk in `/usr/bin/disklist -a`; do
-            if [[ `/usr/sbin/fstyp /dev/dsk/${disk}p1` == 'pcfs' ]]; then
-                /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${disk}p1 \
-                    ${USBMOUNTPOINT};
-                if [[ $? == "0" ]]; then
-                    if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                        if [[ ${DEBUG} == "true" ]]; then
-                            mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                        fi
-                        /usr/sbin/umount ${USBMOUNTPOINT};
-                    else
-                        if [[ ${DEBUG} == "true" ]]; then
-                            mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                        fi
-                        break;
-                    fi
-                elif [[ ${DEBUG} == "true" ]]; then
-                    mount_usb_msg="${mount_usb_msg}\n[debug] unable to mount /dev/dsk/${disk}p1"
-                fi
-            elif [[ ${DEBUG} == "true" ]]; then
-                mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${disk}p1 is not pcfs"
-            fi
-        done
-    fi
-
-    if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-        mount_usb_msg="success"
-
-        zpool list | grep ${SYS_ZPOOL}
-
-        if [[ $? == 0 ]]; then
-            make_usb_copy
-        fi
-
-        echo "Running from USB..." > /dev/console
-        exit 0;
-    fi
-
-    mount_usb_msg="${mount_usb_msg}\n[FATAL] mount_usb(): could not find USB Key"
-    exit 1;
-else
+if [ ${BOOTED_FROM_HDD} -eq 1 ]; then
     # Booted from HDD
     echo "Running from HDD..." > /dev/console
     exit 0
 fi
+
+# The rest only applies to the headnode and computenode, not standalone system
+/bin/bootparams | egrep "^(headnode=true|computenode=true)" >/dev/null || exit $SMF_EXIT_OK
+
+# If we rebooted during an upgrade, we're in deep trouble.
+if [ -d /var/upgrade_in_progress ]; then
+    echo "ERROR: An upgrade was in progress when the system rebooted." \
+        >/dev/console
+    echo "       The system is in an indeterminate state, unable to continue." \
+        >/dev/console
+    exit $SMF_EXIT_ERR_FATAL
+fi
+
+mount_usb_msg=""
+
+if [[ -d /mnt ]]; then
+    chown root:root /mnt
+    chmod 700 /mnt
+else
+    mkdir -m 700 /mnt
+fi
+
+mkdir -p ${USBMOUNTPOINT}
+
+if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
+    mount_usb_msg="already mounted"
+
+    zpool list | grep ${SYS_ZPOOL}
+    if [[ $? == 0 ]]; then
+        make_usb_copy
+        exit $?
+    fi
+
+    echo "Running from USB..." > /dev/console
+    exit 0;
+fi
+
+# First thing to do is to mount the USB key / VMWare disk
+USBKEYS=`/usr/bin/disklist -a`
+for key in ${USBKEYS}; do
+    if [[ `/usr/sbin/fstyp /dev/dsk/${key}p0:1` == 'pcfs' ]]; then
+        /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${key}p0:1 \
+            ${USBMOUNTPOINT};
+        if [[ $? == "0" ]]; then
+            if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
+                if [[ ${DEBUG} == "true" ]]; then
+                    mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
+                fi
+                /usr/sbin/umount ${USBMOUNTPOINT};
+            else
+                if [[ ${DEBUG} == "true" ]]; then
+                    mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
+                fi
+                break;
+            fi
+        elif [[ ${DEBUG} == "true" ]]; then
+            mount_usb_msg="${mount_usb_msg}\n[debug] mount failed for pcfs /dev/dsk/${key}p0:1"
+        fi
+    elif [[ ${DEBUG} == "true" ]]; then
+        mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${key}p0:1 is not pcfs"
+    fi
+done
+
+if [[ ! -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
+    # we're probably VMWare, so we're looking at a non-USB disk.
+    for disk in `/usr/bin/disklist -a`; do
+        if [[ `/usr/sbin/fstyp /dev/dsk/${disk}p1` == 'pcfs' ]]; then
+            /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${disk}p1 \
+                ${USBMOUNTPOINT};
+            if [[ $? == "0" ]]; then
+                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
+                    if [[ ${DEBUG} == "true" ]]; then
+                        mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
+                    fi
+                    /usr/sbin/umount ${USBMOUNTPOINT};
+                else
+                    if [[ ${DEBUG} == "true" ]]; then
+                        mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
+                    fi
+                    break;
+                fi
+            elif [[ ${DEBUG} == "true" ]]; then
+                mount_usb_msg="${mount_usb_msg}\n[debug] unable to mount /dev/dsk/${disk}p1"
+            fi
+        elif [[ ${DEBUG} == "true" ]]; then
+            mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${disk}p1 is not pcfs"
+        fi
+    done
+fi
+
+if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
+    mount_usb_msg="success"
+
+    zpool list | grep ${SYS_ZPOOL}
+
+    if [[ $? == 0 ]]; then
+        make_usb_copy
+    fi
+
+    echo "Running from USB..." > /dev/console
+    exit 0;
+fi
+
+mount_usb_msg="${mount_usb_msg}\n[FATAL] mount_usb(): could not find USB Key"
+exit 1;
diff --git a/lib/svc/method/fs-root b/lib/svc/method/fs-root
--- a/lib/svc/method/fs-root
+++ b/lib/svc/method/fs-root
@@ -22,7 +22,7 @@
 #
 # Copyright (c) 1992, 2010, Oracle and/or its affiliates. All rights reserved.
 # Copyright 2016 Joyent, Inc.
-# Copyright 2016 Erigones, Ltd.
+# Copyright 2017 Erigones, s. r. o.
 #
 
 # Make sure that the libraries essential to this stage of booting can be found.
@@ -66,47 +66,46 @@ if smf_is_nonglobalzone; then
 fi
 
 run_from_usb() {
-    echo "Running from USB live image..." >&2
+	echo "Running from USB live image..." >&2
 
-    /sbin/mount -F ufs -o remount,rw,nologging /devices/ramdisk:a /
-    /usr/sbin/lofiadm -X -a /usr.lgz
+	/sbin/mount -F ufs -o remount,rw,nologging /devices/ramdisk:a /
+	/usr/sbin/lofiadm -X -a /usr.lgz
 
-    #
-    # Prior to mounting /usr, devfsadm is not yet available.  As such, we must
-    # locate the lofi block device node in /devices rather than in /dev.  This
-    # path has changed over time so we try both the old (pre-partition support)
-    # and new paths.
-    #
-    lofi_devices_path='/devices/pseudo/lofi@1:disk'
-    if [ ! -b "$lofi_devices_path" ]; then
-        lofi_devices_path='/devices/pseudo/lofi@0:1'
-        if [ ! -b "$lofi_devices_path" ]; then
-            echo 'could not locate lofi block device in /devices' >&2
-            exit $SMF_EXIT_ERR_FATAL
-        fi
-    fi
+	#
+	# Prior to mounting /usr, devfsadm is not yet available.  As such, we must
+	# locate the lofi block device node in /devices rather than in /dev.  This
+	# path has changed over time so we try both the old (pre-partition support)
+	# and new paths.
+	#
+	lofi_devices_path='/devices/pseudo/lofi@1:disk'
+	if [ ! -b "$lofi_devices_path" ]; then
+		lofi_devices_path='/devices/pseudo/lofi@0:1'
+		if [ ! -b "$lofi_devices_path" ]; then
+			echo 'could not locate lofi block device in /devices' >&2
+			exit $SMF_EXIT_ERR_FATAL
+		fi
+	fi
 
-    if ! /sbin/mount -F ufs -o ro "$lofi_devices_path" /usr; then
-        echo "could not mount /usr from $lofi_devices_path" >&2
-        exit $SMF_EXIT_ERR_FATAL
-    fi
-    return
+	if ! /sbin/mount -F ufs -o ro "$lofi_devices_path" /usr; then
+		echo "could not mount /usr from $lofi_devices_path" >&2
+		exit $SMF_EXIT_ERR_FATAL
+	fi
+
+	return
 }
 
 run_from_hdd() {
-    echo "Running from hard drive..." >&2
-    return
+	echo "Running from hard drive..." >&2
+	return
 }
 
 # mounted() will return 0 if root filesystem is of type ZFS, otherwise
 # we assume that we run from USB
-mounted "/" "-" "zfs" < /etc/mnttab
-if [ $? -eq 0 ]; then
-    run_from_hdd
+if mounted "/" "-" "zfs" < /etc/mnttab; then
+	run_from_hdd
 else
-    run_from_usb
+	run_from_usb
 fi
-
 #
 # Update kernel driver.conf cache with any additional driver.conf
 # files found on /usr, and device permissions from /etc/minor_perm.
diff --git a/lib/svc/method/smartdc-init b/lib/svc/method/smartdc-init
--- a/lib/svc/method/smartdc-init
+++ b/lib/svc/method/smartdc-init
@@ -12,7 +12,7 @@
 
 #
 # Copyright 2016 Joyent, Inc.
-# Copyright 2016 Erigones, Ltd.
+# Copyright 2017 Erigones, s. r. o.
 #
 
 export PS4='[\D{%FT%TZ}] ${BASH_SOURCE}:${LINENO}: ${FUNCNAME[0]:+${FUNCNAME[0]}(): }'
@@ -188,7 +188,7 @@ install_agents7()
 
     rm -f /var/tmp/agents_latest.sh
     curl -k -o /var/tmp/agents_latest.sh \
-        -s $CONFIG_assets_admin_ip:/extra/agents/latest
+        -s "http://${CONFIG_assets_admin_ip}/extra/agents/latest"
 
     [[ ! -f /var/tmp/agents_latest.sh ]] && return 1
     (cd /var/tmp; bash /var/tmp/agents_latest.sh)
@@ -284,7 +284,7 @@ install_config()
     load_sdc_config
 
     curl -k -o /tmp/node.config --silent \
-	$CONFIG_assets_admin_ip:/extra/joysetup/node.config
+        "http://${CONFIG_assets_admin_ip}/extra/joysetup/node.config"
 
     [[ ! -f /tmp/node.config ]] && return 0
     grep datacenter_name /tmp/node.config >/dev/null 2>&1
@@ -315,7 +315,7 @@ update_local_key()
     [ $nkeys -ne 1 ] && return
 
     curl -k -o /var/tmp/cnkey.tgz -f -s \
-        $CONFIG_assets_admin_ip:/extra/usbkey/cnkey.tgz
+        "http://${CONFIG_assets_admin_ip}/extra/usbkey/cnkey.tgz"
     [ ! -f /var/tmp/cnkey.tgz ] && return
 
     local console=$(bootparams | grep ^console= | cut -d= -f2)
@@ -425,12 +425,12 @@ case "$1" in
             USBMOUNT=/`svcprop -p joyentfs/usb_copy_path svc:/system/filesystem/smartdc:default`
         fi
 
-        # No config file (e.g. user quit during interactive configuration), so
-        # treat as if "noimport=true".
-        [[ ! -f $USBMOUNT/config ]] && exit $SMF_EXIT_OK
+	# No config file (e.g. user quit during interactive configuration), so
+	# treat as if "noimport=true".
+	[[ ! -f $USBMOUNT/config ]] && exit $SMF_EXIT_OK
 
         initial_script=${USBMOUNT}/$(grep "^initial_script=" $USBMOUNT/config.inc/generic 2>/dev/null | cut -d'=' -f2-)
-        if [ -f ${initial_script} ] && [ -n ${initial_script} ] && [ -e ${initial_script} ]; then
+        if [[ -n ${initial_script} ]] && [[ -e ${initial_script} ]]; then
             # Execute the script
             ${initial_script}
             result=$?
@@ -445,68 +445,70 @@ case "$1" in
         fi
     fi
     if /bin/bootparams | grep "^computenode=true" > /dev/null 2>&1; then
-            set_default_fw_rules
+        set_default_fw_rules
     else
-        install_config
+	install_config
+
         # If this CN was running 6.5.x and has now been booted onto 7.0, we
         # need to uninstall the old 6.5.x agents and install the new 7.0 agents.
         if [[ -d /opt/smartdc/agents/modules && \
             ! -d  /opt/smartdc/agents/lib ]]; then
-                # During upgrade (or even before) we know the config file should
-                # have been upgraded to include the imgapi_domain entry. If that
-                # didn't happen, fail now.
-                egrep -s imgapi_domain /opt/smartdc/config/node.config
-                if [ $? -ne 0 ]; then
-                        echo "ERROR: the local config file was not updated for upgrade."
-                        exit $SMF_EXIT_ERR_FATAL
-                fi
 
-                # Enable new ZFS features. The pool will no longer be usable on 6.5
-                zpool set feature@async_destroy=enabled zones
-                zpool set feature@empty_bpobj=enabled zones
-                zpool set feature@lz4_compress=enabled zones
+	    # During upgrade (or even before) we know the config file should
+	    # have been upgraded to include the imgapi_domain entry. If that
+	    # didn't happen, fail now.
+	    egrep -s imgapi_domain /opt/smartdc/config/node.config
+	    if [ $? -ne 0 ]; then
+                echo "ERROR: the local config file was not updated for upgrade."
+                exit $SMF_EXIT_ERR_FATAL
+	    fi
 
-                # Convert to 7.0-style cores datasets
-                zfs destroy -r zones/cores
-                zfs create -o compression=lz4 -o mountpoint=none zones/cores
-                for i in `zoneadm list -c`
-                do
-                    zfs destroy -rf zones/$i/cores
-                    zfs create -o quota=100g -o mountpoint=/zones/$i/cores \
-                        zones/cores/$i
-                done
+            # Enable new ZFS features. The pool will no longer be usable on 6.5
+            zpool set feature@async_destroy=enabled zones
+            zpool set feature@empty_bpobj=enabled zones
+            zpool set feature@lz4_compress=enabled zones
 
-                echo "Upgrading the system's agents" > /dev/console
+            # Convert to 7.0-style cores datasets
+            zfs destroy -r zones/cores
+            zfs create -o compression=lz4 -o mountpoint=none zones/cores
+            for i in `zoneadm list -c`
+            do
+                zfs destroy -rf zones/$i/cores
+                zfs create -o quota=100g -o mountpoint=/zones/$i/cores \
+                    zones/cores/$i
+            done
 
-                # disable the smartdc agent svcs
-                echo "stopping svcs"
-                for i in `svcs -a | nawk '/smartdc\/agent/{print $3}'`
-                do
-                [[ "$i" == "svc:/smartdc/agent/ur:default" || \
-                   "$i" == "svc:/smartdc/agent/metadata:default" ]] && \
-                    continue
-                svcadm disable $i
-                done
+            echo "Upgrading the system's agents" > /dev/console
 
-                uninstall_agents6
-                install_agents7
+	    # disable the smartdc agent svcs
+	    echo "stopping svcs"
+	    for i in `svcs -a | nawk '/smartdc\/agent/{print $3}'`
+	    do
+		[[ "$i" == "svc:/smartdc/agent/ur:default" || \
+		   "$i" == "svc:/smartdc/agent/metadata:default" ]] && \
+		    continue
+		svcadm disable $i
+	    done
 
-                create_setup_status
-                sysinfo -u
-                rm -f /tmp/.ur-startup
-                svcadm restart ur
+            uninstall_agents6
+            install_agents7
 
-                update_local_key
-                configure_imgadm
+            create_setup_status
+            sysinfo -u
+            rm -f /tmp/.ur-startup
+            svcadm restart ur
 
-                echo "Upgrade done" > /dev/console
-            fi
+            update_local_key
+            configure_imgadm
+
+            echo "Upgrade done" > /dev/console
+        fi
     fi
 
     configure_fwadm
     configure_vmadm
 
-    if /bin/bootparams | egrep "^(headnode=true|computenode=true)" > /dev/null 2>&1; then
+	if /bin/bootparams | egrep "^(headnode=true|computenode=true)" > /dev/null 2>&1; then
         # Unmount only if running from live image
         [ ${BOOTED_FROM_HDD} -eq 0 ] && /usr/sbin/umount $USBMOUNT
     fi
