merge changes from upstream 20190829 before moving everything into smartos-live and illumos-joyent (phasing out this repo)

diff --git a/lib/svc/method/fs-joyent b/lib/svc/method/fs-joyent
--- a/lib/svc/method/fs-joyent
+++ b/lib/svc/method/fs-joyent
@@ -25,6 +25,7 @@ fatal()
 
 . /lib/svc/share/smf_include.sh
 . /lib/svc/share/fs_include.sh
+. /lib/sdc/usb-key.sh
 
 # first of all, if we aren't the global zone this doesn't make any sense to run
 
@@ -70,56 +71,6 @@ function mount_zfs
     echo ${output} 1>&2
 }
 
-function make_usb_copy_if_possible
-{
-    [[ -n "${SYS_ZPOOL}" ]] || fatal "don't know system zpool name"
-
-    zpool list -Ho name | grep "^${SYS_ZPOOL}\$"
-    if [[ $? != 0 ]]; then
-        echo "skipping USB copy setup: no ${SYS_ZPOOL} zpool" >/dev/console
-        # Still return OK, because this is the expected case for first headnode
-        # boot.
-        return 0
-    fi
-
-    USBDATASET=${SYS_ZPOOL}/usbkey
-    if ! zfs list -Ho name | grep "^${USBDATASET}\$" >/dev/null; then
-        echo "skipping USB copy setup: no zones/usbkey dataset" >/dev/console
-        # Still return OK, because as of HEAD-2343 a CN being converted to a HN
-        # will not yet have this dataset on its first boot as an HN.
-        return 0
-    fi
-
-    echo "" > /dev/console
-    echo "Moving files from USB boot device onto disk storage." > /dev/console
-    echo "This may take several minutes." > /dev/console
-    echo "" > /dev/console
-    echo "" > /dev/console
-
-    mkdir ${COPYINPOINT}
-    mount_zfs ${USBDATASET} ${COPYINPOINT}
-
-    $(cd ${USBMOUNTPOINT}; rsync -a --log-file=/dev/console --exclude private --exclude os * ${COPYINPOINT})
-    if [[ -d ${USBMOUNTPOINT}/os ]]; then
-        (cd ${USBMOUNTPOINT}/os ; \
-            for dir in $(ls -d *); do
-                # source comes from pcfs which we've got lowering the case
-                # of everything, but we normally use capital T and Z for
-                # buildstamp, so fix it here.
-                source_dir=${dir}
-                target_dir=$(echo ${dir} | tr "[:lower:]" "[:upper:]")
-                mkdir -p ${COPYINPOINT}/os
-                echo "Copying: ${source_dir}/ ${COPYINPOINT}/os/${target_dir}" > /dev/console
-                rsync -a ${source_dir}/ ${COPYINPOINT}/os/${target_dir}
-            done
-        )
-    fi
-
-    echo "" > /dev/console
-    echo "Done copying files from USB device" > /dev/console
-    return 0
-}
-
 # Assume the system zpool is zones, but if a different system pool
 # identifies itself (by virtue of the .system_pool file being present in the
 # pool's root dataset), then use that system pool instead.
@@ -130,11 +81,6 @@ BOOTED_FROM_HDD=1
 
 # Placeholder for current Boot Environment name
 BENAME="dcos-1"
-
-# USB mount points
-USBMOUNTPOINT=/mnt/`svcprop -p "joyentfs/usb_mountpoint" ${SMF_FMRI}`
-COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
-DEBUG=`svcprop -p "joyentfs/debug" ${SMF_FMRI}`
 
 # Try to determine if we are booted from HDD
 # Do this by finding out whether "/" is being mounted as "zfs"
@@ -162,24 +108,20 @@ if [ $? -ne 0 ]; then
          pools=$(zpool import | grep "pool:" | awk '{print $2}')
     fi
 
-    # Import pools found or requested. Also determine the system pool
-    # when we run from live image.
     for pool in $pools; do
         zpool import -f $pool
         # Due to early, failed attempts to support the filesystem_limits
         # feature we now need to ensure the dependent feature is enabled.
         zpool set feature@extensible_dataset=enabled $pool
-        # Determine the system pool (only ONE can be system pool) when
-        # we run from live image
         if [[ ${BOOTED_FROM_HDD} -ne 1 && -f /${pool}/.system_pool ]]; then
             SYS_ZPOOL=$pool
         fi
     done
 
-    # Explicitly set features and mount system zpool default dataset
-    zpool set feature@extensible_dataset=enabled ${SYS_ZPOOL}
-    zfs mount ${SYS_ZPOOL}
-
+#    # Explicitly set features and mount system zpool default dataset
+#    zpool set feature@extensible_dataset=enabled ${SYS_ZPOOL}
+#    zfs mount ${SYS_ZPOOL}
+#
     svccfg -s svc:/system/smartdc/init setprop \
         config/zpool=${SYS_ZPOOL}
     svccfg -s svc:/system/smartdc/init:default refresh
@@ -214,12 +156,6 @@ if [ $? -ne 0 ]; then
         # Stash the SUNWdefault.xml file so we can update the
         # persistent version after mounting zones/config.
         cp /etc/zones/SUNWdefault.xml /tmp/
-
-        if [[ -n $(/bin/bootparams | grep '^headnode=true') || \
-            -n $(/bin/bootparams | grep '^smartos=true') ]]; then
-            mkdir /usbkey
-            mount_zfs ${SYS_ZPOOL}/usbkey /usbkey
-        fi
 
         if [ ${BOOTED_FROM_HDD} -eq 0 ]; then
             VARDS="${SYS_ZPOOL}/var"
@@ -262,10 +198,17 @@ if [ $? -ne 0 ]; then
             mount -O -F lofs /var/svc/manifest/site /opt/smartdc/agents/smf
         fi
 
+        if [[ -n $(/bin/bootparams | grep '^headnode=true') || \
+            -n $(/bin/bootparams | grep '^smartos=true') ]]; then
+            mkdir /usbkey
+            mount_zfs ${SYS_ZPOOL}/usbkey /usbkey
+        fi
+
         _swapdev=/dev/zvol/dsk/${SYS_ZPOOL}/swap
         if ! swap -l | grep -q ^${_swapdev}; then
             swap -a ${_swapdev} || fatal "failed to configure swap device"
         fi
+
 
         #
         # Configure the dump device on top of a ZFS volume.  In addition to the
@@ -281,24 +224,24 @@ if [ $? -ne 0 ]; then
             fatal "failed to set checksum=noparity on dump zvol"
         zpool set feature@multi_vdev_crash_dump=enabled ${SYS_ZPOOL} || \
             fatal "failed to enable multi_vdev_crash_dump ZFS feature"
-	dumpadm -y -d /dev/zvol/dsk/${SYS_ZPOOL}/dump || \
+        dumpadm -y -d /dev/zvol/dsk/${SYS_ZPOOL}/dump || \
             fatal "failed to configure dump device"
 
-	zfs list -H -o name ${SYS_ZPOOL}/cores/global >/dev/null 2>&1
-	if [ $? -ne 0 ]; then
-	    # Booting for the first time on a CN whose cores dataset is setup
-	    # in the 6.x style.  Convert to the new style.
-	    zfs destroy -r ${SYS_ZPOOL}/cores
-	    zfs create -o compression=gzip -o mountpoint=none ${SYS_ZPOOL}/cores
-	    zfs create -o quota=10g -o mountpoint=/${SYS_ZPOOL}/global/cores \
-	        ${SYS_ZPOOL}/cores/global
-	fi
+        zfs list -H -o name ${SYS_ZPOOL}/cores/global >/dev/null 2>&1
+        if [ $? -ne 0 ]; then
+            # Booting for the first time on a CN whose cores dataset is setup
+            # in the 6.x style.  Convert to the new style.
+            zfs destroy -r ${SYS_ZPOOL}/cores
+            zfs create -o compression=gzip -o mountpoint=none ${SYS_ZPOOL}/cores
+            zfs create -o quota=10g -o mountpoint=/${SYS_ZPOOL}/global/cores \
+                ${SYS_ZPOOL}/cores/global
+        fi
 
-	[[ ! -d /cores ]] && ln -s /${SYS_ZPOOL}/global/cores /cores
+        [[ ! -d /cores ]] && ln -s /${SYS_ZPOOL}/global/cores /cores
 
-	[[ -f /${SYS_ZPOOL}/currbooted ]] && \
+        [[ -f /${SYS_ZPOOL}/currbooted ]] && \
             mv /${SYS_ZPOOL}/currbooted /${SYS_ZPOOL}/lastbooted
-	uname -v >/${SYS_ZPOOL}/currbooted
+        uname -v >/${SYS_ZPOOL}/currbooted
     fi
 fi
 
@@ -325,7 +268,8 @@ if [ -d /var/upgrade_in_progress ]; then
     exit $SMF_EXIT_ERR_FATAL
 fi
 
-mount_usb_msg=""
+COPYINPOINT=`svcprop -p "joyentfs/usb_copy_path" ${SMF_FMRI}`
+DEBUG=`svcprop -p "joyentfs/debug" ${SMF_FMRI}`
 
 if [[ -d /mnt ]]; then
     chown root:root /mnt
@@ -334,72 +278,60 @@ else
     mkdir -m 700 /mnt
 fi
 
-mkdir -p ${USBMOUNTPOINT}
+function make_usb_copy_if_possible
+{
+    [[ -n "${SYS_ZPOOL}" ]] || fatal "don't know system zpool name"
 
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="already mounted"
-    make_usb_copy_if_possible
-    exit $?
-fi
-
-# First thing to do is to mount the USB key / VMWare disk
-USBKEYS=`/usr/bin/disklist -a`
-for key in ${USBKEYS}; do
-    if [[ `/usr/sbin/fstyp /dev/dsk/${key}p0:1` == 'pcfs' ]]; then
-        /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${key}p0:1 \
-            ${USBMOUNTPOINT};
-        if [[ $? == "0" ]]; then
-            if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                if [[ ${DEBUG} == "true" ]]; then
-                    mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                fi
-                /usr/sbin/umount ${USBMOUNTPOINT};
-            else
-                if [[ ${DEBUG} == "true" ]]; then
-                    mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${key}p0:1"
-                fi
-                break;
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] mount failed for pcfs /dev/dsk/${key}p0:1"
-        fi
-    elif [[ ${DEBUG} == "true" ]]; then
-        mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${key}p0:1 is not pcfs"
+    zpool list -Ho name | grep "^${SYS_ZPOOL}\$"
+    if [[ $? != 0 ]]; then
+        echo "skipping USB copy setup: no ${SYS_ZPOOL} zpool" >/dev/console
+        # Still return OK, because this is the expected case for first headnode
+        # boot.
+        return 0
     fi
-done
 
-if [[ ! -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    # we're probably VMWare, so we're looking at a non-USB disk.
-    for disk in `/usr/bin/disklist -a`; do
-        if [[ `/usr/sbin/fstyp /dev/dsk/${disk}p1` == 'pcfs' ]]; then
-            /usr/sbin/mount -F pcfs -o foldcase,noatime /dev/dsk/${disk}p1 \
-                ${USBMOUNTPOINT};
-            if [[ $? == "0" ]]; then
-                if [[ ! -f ${USBMOUNTPOINT}/.joyliveusb ]]; then
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] didn't find ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                    fi
-                    /usr/sbin/umount ${USBMOUNTPOINT};
-                else
-                    if [[ ${DEBUG} == "true" ]]; then
-                        mount_usb_msg="${mount_usb_msg}\n[debug] found ${USBMOUNTPOINT}/.joyliveusb on pcfs /dev/dsk/${disk}p1"
-                    fi
-                    break;
-                fi
-            elif [[ ${DEBUG} == "true" ]]; then
-                mount_usb_msg="${mount_usb_msg}\n[debug] unable to mount /dev/dsk/${disk}p1"
-            fi
-        elif [[ ${DEBUG} == "true" ]]; then
-            mount_usb_msg="${mount_usb_msg}\n[debug] /dev/dsk/${disk}p1 is not pcfs"
-        fi
-    done
+    USBDATASET=${SYS_ZPOOL}/usbkey
+    if ! zfs list -Ho name | grep "^${USBDATASET}\$" >/dev/null; then
+        echo "skipping USB copy setup: no zones/usbkey dataset" >/dev/console
+        # Still return OK, because as of HEAD-2343 a CN being converted to a HN
+        # will not yet have this dataset on its first boot as an HN.
+        return 0
+    fi
+
+    echo "" > /dev/console
+    echo "Moving files from USB boot device onto disk storage." > /dev/console
+    echo "This may take several minutes." > /dev/console
+    echo "" > /dev/console
+    echo "" > /dev/console
+
+    mkdir ${COPYINPOINT}
+    mount_zfs ${USBDATASET} ${COPYINPOINT}
+
+    (cd ${USBMOUNTPOINT}; rsync -av --log-file=/dev/console --exclude private --exclude os * ${COPYINPOINT})
+    if [[ -d ${USBMOUNTPOINT}/os ]]; then
+        (cd ${USBMOUNTPOINT}/os ; \
+            for dir in $(ls -d *); do
+                # source comes from pcfs which we've got lowering the case
+                # of everything, but we normally use capital T and Z for
+                # buildstamp, so fix it here.
+                source_dir=${dir}
+                target_dir=$(echo ${dir} | tr "[:lower:]" "[:upper:]")
+                mkdir -p ${COPYINPOINT}/os
+                echo "Copying: ${source_dir}/ ${COPYINPOINT}/os/${target_dir}" > /dev/console
+                rsync -a ${source_dir}/ ${COPYINPOINT}/os/${target_dir}
+            done
+        )
+    fi
+
+    echo "" > /dev/console
+    echo "Done copying files from USB device" > /dev/console
+    return 0
+}
+
+USBMOUNTPOINT=$(mount_usb_key "")
+if [[ $? -ne 0 ]]; then
+    fatal "couldn't mount USB key"
 fi
 
-if [[ -f "${USBMOUNTPOINT}/.joyliveusb" ]]; then
-    mount_usb_msg="success"
-    make_usb_copy_if_possible
-    exit $?
-fi
-
-mount_usb_msg="${mount_usb_msg}\n[FATAL] mount_usb(): could not find USB Key"
-exit 1;
+make_usb_copy_if_possible
+exit $?
diff --git a/lib/svc/method/net-physical b/lib/svc/method/net-physical
--- a/lib/svc/method/net-physical
+++ b/lib/svc/method/net-physical
@@ -75,64 +75,10 @@ function add_active_aggr_links
     done
 }
 
-function log_if_state
-{
-    set -o xtrace
-    echo "== debug start: $1 =="
-    nictagadm list
-    if ! /usr/sbin/dladm show-phys; then
-        echo "WARNING: 'dladm show-phys' failed"
-    fi
-    # NOTE: DO NOT do a 'dladm show-linkprop' when using the bnx driver,
-    # as it puts it into an unusable state!
-    if ! /sbin/ifconfig -a; then
-        echo "WARNING: 'ifconfig -a' failed"
-    fi
-    echo "== debug end: $1 =="
-}
-
-# Gets the link state for the given interface
-function get_link_state
-{
-    set -o xtrace
-    link_state=$(/usr/sbin/dladm show-phys -po state $1 2>/dev/null)
-}
-
 # Waits for up to 10 seconds for the link state to change to the given value
 function wait_for_admin_nic_state
 {
-    set -o xtrace
-    echo "wait_for_admin_nic_state: waiting for state '$1'"
-    i=0
-    get_link_state ${SYSINFO_NIC_admin}
-    while [[ "$link_state" != "$1" ]] && [[ $i -ne 10 ]]; do
-        sleep 1
-        echo "  $i: link_state=$link_state"
-        ((i++))
-        get_link_state ${SYSINFO_NIC_admin}
-    done
-    echo "wait_for_admin_nic_state: finished in state '$link_state'"
-}
-
-function valid_mtu
-{
-    set -o xtrace
-    typeset tag mtu
-
-    tag="$1"
-    mtu="$2"
-
-    if ! [[ $mtu =~ [1-9][0-9][0-9][0-9] ]] ; then
-        echo "Invalid mtu specified for tag $tag: $mtu"
-        echo "Valid MTU range is from 1500-9000"
-        exit $SMF_EXIT_ERR_FATAL
-    fi
-
-    if [[ $mtu -gt 9000 || $mtu -lt 1500 ]]; then
-        echo "Invalid mtu specified for tag $tag: $mtu"
-        echo "Valid MTU range is from 1500-9000"
-        exit $SMF_EXIT_ERR_FATAL
-    fi
+    wait_for_nic_state "${SYSINFO_NIC_admin}" "$1"
 }
 
 # Plumbs the admin interface, and attempts to work around poorly-behaved
@@ -438,14 +384,14 @@ function setup_mtu
             exit $SMF_EXIT_ERR_FATAL
         fi
 
-	#
-	# Check the current MTU of the device. To help out devices which
-	# don't support the setting of the MTU (here's looking at you
-	# bnx), if the MTU is identical to its default, don't do
-	# anything and save the poor folks stuck with bnx some grief.
-	#
-	curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
-	[[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
+        #
+        # Check the current MTU of the device. To help out devices which
+        # don't support the setting of the MTU (here's looking at you
+        # bnx), if the MTU is identical to its default, don't do
+        # anything and save the poor folks stuck with bnx some grief.
+        #
+        curmtu=$(/usr/sbin/dladm show-linkprop -c -o value -p mtu ${link})
+        [[ $? -eq 0 ]] && [[ "$curmtu" -eq "${mtus[$mac]}" ]] && continue
 
         if ! /usr/sbin/dladm set-linkprop -p mtu=${mtus[$mac]} ${link}; then
             echo "Failed to set mtu to ${mtus[$mac]} for link ${link}"
@@ -472,8 +418,9 @@ function plumbif
 }
 
 if smf_is_globalzone; then
-
-    /usr/sbin/dladm init-phys
+    EARLY_ADMIN=
+    [[ -f /etc/svc/volatile/.early_admin_setup ]] && EARLY_ADMIN=1
+    [[ -n "$EARLY_ADMIN" ]] || /usr/sbin/dladm init-phys
 
     # The next command is for logging purposes only
     log_if_state before
@@ -493,6 +440,10 @@ if smf_is_globalzone; then
         fi
 
         load_boot_file_config
+
+        # NOTE: some of the routes boot_file_config_init tries to add may
+        # fail if they are admin network routes added by the
+        # network/early-admin service.  This is expected and not a problem.
         boot_file_config_init
     else
         # Load config variables with CONFIG_ prefix,
@@ -591,9 +542,18 @@ if smf_is_globalzone; then
         exit ${SMF_EXIT_ERR_CONFIG}
     fi
 
+    [[ -z "$EARLY_ADMIN" ]] && [[ -z "${nic_admin_on_etherstub}" ]] && plumb_admin
     eval "nic_admin_on_etherstub=\${SYSINFO_Etherstub_${SYSINFO_NIC_admin}_NIC_Names}"
 
-    [[ -z "${nic_admin_on_etherstub}" ]] && plumb_admin
+    # If we performed early configuration of the admin network and
+    # the admin interface is on a link aggregation, the aggregation
+    # has already been configured.  Add it to the list of active aggrs
+    # so the checks in vnic_up[6] are aware of it.
+    if [[ -n "$EARLY_ADMIN" && "${SYSINFO_NIC_admin}" =~ aggr[0-9]+$ ]]; then
+        eval "macs=\${SYSINFO_Aggregation_${SYSINFO_NIC_admin}_MACs}"
+
+        add_active_aggr_links ${SYSINFO_NIC_admin} $macs
+    fi
 
     # Prefer the config file for admin nic values, but use
     # bootparams if present
@@ -633,6 +593,9 @@ if smf_is_globalzone; then
 
     if [[ $admin_ip == 'none' ]]; then
         echo 'INFO: not configuring IP on admin interface (admin_ip=none)'
+    elif [[ -n "$EARLY_ADMIN" ]]; then
+        echo 'INFO: admin interface already configured (early setup)'
+        ADMIN_NIC_UP=true
     elif [[ -n $admin_ip ]] && [[ -n $admin_netmask ]]; then
         /sbin/ifconfig ${admin_iface_active} inet ${admin_ip} \
             netmask ${admin_netmask} up
@@ -676,7 +639,7 @@ if smf_is_globalzone; then
         fi
     fi
 
-    if [[ -n ${admin_ip6} ]]; then
+    if [[ -n ${admin_ip6} && -z "$EARLY_ADMIN" ]]; then
         # Plumb interface for inet6
         ifconfig ${admin_iface_active} inet6 \
             plumb mtu ${CONFIG_admin_mtu:-1500} up
